# Generated by Django 2.0.7 on 2018-07-14 18:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
